version: "3.1"
services:
  notifier:
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"